/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chrissoftwareengineeringwork;

import java.util.Iterator;
import javax.swing.JOptionPane;

public class RemoveEmployeeUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private AdminMainMenuUI parent;
    public RemoveEmployeeUI(AdminMainMenuUI p) {
        parent = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        title = new javax.swing.JLabel();
        lblEmpID = new javax.swing.JLabel();
        empNumber = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setText("Remove Employee");

        lblEmpID.setText("Employee Number: ");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        delete.setText("Remove Employee");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(title)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEmpID)
                            .addGap(18, 18, 18)
                            .addComponent(empNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(title)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpID)
                    .addComponent(empNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(delete))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(parent.getEmpList().size() == 1)
        {
            JOptionPane.showMessageDialog(null, "There is only one employee in the system!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Integer i = 0;
            Employee remove = null;
            Iterator<Employee> it = parent.getEmpList().iterator();
        
            while(it.hasNext())
            {
                Employee emp = it.next();
                if(empNumber.getText().equals(Integer.toString(emp.getSysEmpID())))
                {
                    i = 1;
                    remove = emp;
                    JOptionPane.showMessageDialog(null, "Employee number " + emp.getSysEmpID() + " removed.", "Done", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    parent.setVisible(true);
                
                }
            }
            parent.getEmpList().remove(remove);
            if(i == 0)
            {
                JOptionPane.showMessageDialog(null, "Employee does not exist!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }                                      

    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
        this.setVisible(false);
        parent.setVisible(true);
    }                                    

    // Variables declaration - do not modify                     
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JTextField empNumber;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel title;
    // End of variables declaration                   
}