package chrissoftwareengineeringwork;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chris
 */
public class UpdateEmployeeUI extends javax.swing.JFrame {

    private AdminMainMenuUI parent;
    private Employee emp;
    public UpdateEmployeeUI(AdminMainMenuUI p) 
    {
        parent = p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        stageButton = new javax.swing.JButton();
        lblFName = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        lblSName = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        lblDateOfBirth = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dayOfBirth = new javax.swing.JSpinner();
        monthOfBirth = new javax.swing.JSpinner();
        yearOfBirth = new javax.swing.JSpinner();
        lblGender = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        lblEmpType = new javax.swing.JLabel();
        empType = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        lblNatInsuranceNumber = new javax.swing.JLabel();
        natInsuranceNo = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        lblAddrLn1 = new javax.swing.JLabel();
        addrLn1 = new javax.swing.JTextField();
        lblAddrLn2 = new javax.swing.JLabel();
        addrLn2 = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        lblCounty = new javax.swing.JLabel();
        county = new javax.swing.JTextField();
        lblPostcode = new javax.swing.JLabel();
        postcode = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        update = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Staff ID", "First Name", "Surname", "Employee Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        
        
        for(Employee emp : parent.getEmpList())
        {
            String empID = Integer.toString(emp.getSysEmpID());
            Object[] row = new Object[]
            {
                empID, emp.getFName(), emp.getSName(), emp.getEmpType()
            };
            model.addRow(row);
        }
        
        employeeTable.setModel(model);
        
        jScrollPane1.setViewportView(employeeTable);

        stageButton.setText(">>>");

        lblFName.setText("First Name:");

        lblSName.setText("Surname:");

        lblDateOfBirth.setText("D.O.B:");

        jLabel1.setText("  Day           Month         Year");

        dayOfBirth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        monthOfBirth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        yearOfBirth.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2100, 1));

        lblGender.setText("Gender:");

        male.setText("Male");

        female.setText("Female");

        lblEmpType.setText("Emp Type:");

        empType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caretaker", "Manager", "Admin" }));

        lblEmail.setText("Email:");

        lblNatInsuranceNumber.setText("N.I Number");

        lblPassword.setText("Password:");

        lblAddrLn1.setText("Addr Line 1:");

        lblAddrLn2.setText("Addr Line 2:");

        lblCity.setText("City:");

        lblCounty.setText("County:");

        lblPostcode.setText("Postcode:");

        back.setText("Back");

        update.setText("Update Employee");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Update Employee Details");
        
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        
        stageButton.setText(">>>");
        stageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageButtonActionPerformed(evt);
            }
        });
        
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFName)
                                    .addComponent(lblSName)
                                    .addComponent(lblDateOfBirth)
                                    .addComponent(lblEmpType)
                                    .addComponent(lblGender)
                                    .addComponent(lblEmail)
                                    .addComponent(lblNatInsuranceNumber)
                                    .addComponent(lblPassword)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(stageButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(natInsuranceNo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(dayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(monthOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(yearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(female))
                                    .addComponent(surname, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAddrLn1)
                                .addGap(18, 18, 18)
                                .addComponent(addrLn1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddrLn2)
                                    .addComponent(lblCity)
                                    .addComponent(lblCounty)
                                    .addComponent(lblPostcode))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addrLn2)
                                    .addComponent(city)
                                    .addComponent(county)
                                    .addComponent(postcode)))
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(stageButton)
                        .addGap(225, 225, 225))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFName)
                            .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddrLn1)
                            .addComponent(addrLn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSName)
                            .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAddrLn2)
                            .addComponent(addrLn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblCity)
                            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dayOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDateOfBirth))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCounty))
                            .addComponent(county, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGender)
                                    .addComponent(male)
                                    .addComponent(female))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmpType)
                                    .addComponent(empType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmail)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(update))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNatInsuranceNumber)
                                    .addComponent(natInsuranceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(back))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPassword)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPostcode)
                                    .addComponent(postcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(155, 155, 155))))))
        );

        pack();
    }// </editor-fold>                        

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        this.setVisible(false);
        parent.setVisible(true);
    }
    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        parent.getEmpList().remove(emp);
        emp.setFName(fName.getText());
        emp.setSName(surname.getText());
        String dob = dayOfBirth.getValue().toString() + "/" + monthOfBirth.getValue().toString() + "/" + yearOfBirth.getValue().toString();
        emp.setDateOfBirth(dob);
        if(male.isSelected())
        {
            emp.setGender("male");
        }
        else
        {
            emp.setGender("female");
        }
        emp.setEmpType(empType.getSelectedItem().toString());
        emp.setEmail(email.getText());
        emp.setNatInsuranceNo(natInsuranceNo.getText());
        emp.setAddrLn1(addrLn1.getText());
        emp.setAddrLn2(addrLn2.getText());
        emp.setAddrCity(city.getText());
        emp.setAddrCounty(county.getText());
        emp.setAddrPostcode(postcode.getText());
        emp.setSysPassword(String.valueOf(password.getPassword()));
        parent.getEmpList().add(emp);
        System.out.println("Employee Updated" + parent.getEmpList().size());
    }
    
    
    private void stageButtonActionPerformed(java.awt.event.ActionEvent evt) 
    {                                         
        Integer empID = Integer.parseInt(employeeTable.getModel().getValueAt(employeeTable.getSelectedRow(), 0).toString());
        for(Employee emp : parent.getEmpList())
        {
            this.emp = emp;
            if(emp.getSysEmpID() == empID)
            {
                
                fName.setText(emp.getFName());
                surname.setText(emp.getSName());
                String dob = new String(emp.getDateOfBirth());
                String[] strings = dob.split("/");
                String day1 = strings[0];
                String month1 = strings[1];
                String year1 = strings[2];
                Integer day = Integer.parseInt(day1);
                Integer month = Integer.parseInt(month1);
                Integer year = Integer.parseInt(year1);
                dayOfBirth.setValue(day);
                monthOfBirth.setValue(month);
                yearOfBirth.setValue(year);
                if(emp.getGender() == "Male")
                {
                    male.setSelected(true);
                    female.setSelected(false);
                }
                else
                {
                    male.setSelected(false);
                    female.setSelected(true);
                }
                empType.setSelectedItem(emp.getEmpType());
                email.setText(emp.getEmail());
                natInsuranceNo.setText(emp.getNatInsuranceNo());
                addrLn1.setText((emp.getAddrLn1()));
                addrLn2.setText(emp.getAddrLn2());
                city.setText(emp.getAddrCity());
                county.setText(emp.getAddrCounty());
                postcode.setText(emp.getAddrPostcode());
                password.setText(emp.getSysPassword());
            }
        }
    }     

    // Variables declaration - do not modify                     
    private javax.swing.JTextField addrLn1;
    private javax.swing.JTextField addrLn2;
    private javax.swing.JButton back;
    private javax.swing.JTextField city;
    private javax.swing.JTextField county;
    private javax.swing.JSpinner dayOfBirth;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> empType;
    private javax.swing.JTable employeeTable;
    private javax.swing.JTextField fName;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddrLn1;
    private javax.swing.JLabel lblAddrLn2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCounty;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpType;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblNatInsuranceNumber;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPostcode;
    private javax.swing.JLabel lblSName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton male;
    private javax.swing.JSpinner monthOfBirth;
    private javax.swing.JTextField natInsuranceNo;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField postcode;
    private javax.swing.JButton stageButton;
    private javax.swing.JTextField surname;
    private javax.swing.JButton update;
    private javax.swing.JSpinner yearOfBirth;
    // End of variables declaration                   
}
