/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capytec;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
/**
 *
 * @author steve
 */

public class TaskLogging extends javax.swing.JFrame {

    /**
     * Creates new form TaskLogging
     */
    public TaskLogging() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("log");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("find");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("example");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);
        jList1.getAccessibleContext().setAccessibleParent(jButton1);

        jButton4.setText("edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton5.setText("edit selected task");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(141, 141, 141)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("panel");
        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // LOG:
        LogTask.run();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // FIND:

        ArrayList tasks = new ArrayList();
        
        Connection dbConn = connection.connect();

        Statement stmt = null;
        String query = "SELECT * FROM tasks WHERE Completed = 'y'";

        try {
            
        stmt = dbConn.createStatement();    
        ResultSet rs = stmt.executeQuery(query);
        
        while (rs.next()) {
            int TaskID = rs.getInt("taskID");
            int AllocatedTo = rs.getInt("Allocated");
            int TaskPriority = rs.getInt("Priority");
            int SignedOffBy = rs.getInt("SignOff");
            String TaskDesc = rs.getString("Description");
            String DateCreated = rs.getString("DateCreated");
            String SignOffLevel = rs.getString("SignOffLevel");
            float PhysDemRating = rs.getFloat("Demand");
            float TaskDuration = rs.getFloat("Duration");
            
            tasks.add(TaskID + "\t" + AllocatedTo +
                            "\t" + TaskPriority + "\t" + SignedOffBy +
                            "\t" + TaskDesc + "\t" + DateCreated +
                            "\t" + SignOffLevel + "\t" + PhysDemRating +
                            "\t" + TaskDuration);
        }
        
        System.out.println("Contents of completed tasks: " + tasks);
        // print out completed tasks format into list?
    } catch (SQLException e ) {
        System.err.println ("unsuccessful\n");
    } 
                      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // EXAMPLE:
        
        DefaultListModel listModel = new DefaultListModel();

        //ArrayList tasks = new ArrayList();
        
        Connection dbConn = connection.connect();

        Statement stmt = null;
        String query = "SELECT * FROM tasks";

        try {
        stmt = dbConn.createStatement();    
        ResultSet rs = stmt.executeQuery(query);
        while (rs.next()) {
            int TaskID = rs.getInt("taskID");
            int AllocatedTo = rs.getInt("Allocated");
            int TaskPriority = rs.getInt("Priority");
            int SignedOffBy = rs.getInt("SignOff");
            String TaskDesc = rs.getString("Description");
            String DateCreated = rs.getString("DateCreated");
            String SignOffLevel = rs.getString("SignOffLevel");
            float PhysDemRating = rs.getFloat("Demand");
            float TaskDuration = rs.getFloat("Duration");
            
            //listModel.addElement(TaskID + "\t" + AllocatedTo +
            //                "\t" + TaskPriority + "\t" + SignedOffBy +
            //                "\t" + TaskDesc + "\t" + DateCreated +
            //                "\t" + SignOffLevel + "\t" + PhysDemRating +
            //                "\t" + TaskDuration);
            
            listModel.addElement(TaskID + "\t" + " " + AllocatedTo + " " + "\t" + DateCreated);
            
            // set a variable to record allocated to, change to name, selected from list
            // action listener to change list on click            
        }
        
        jList1.setModel(listModel);
        //System.out.println("Contents of tasks: " + tasks);
        // next int next string etc... get task ID / name?
    } catch (SQLException e ) {
        System.err.println ("unsuccessful\n");
    } 
             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // EDIT
        
        // view tasks completed
        
        // select which one to change
        
        // commit changes or cancel
        
        // display pop up notifying of changes made
        
        // restrict based on privilieges?        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void run() {
        new TaskLogging().setVisible(true);
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
